[emacs-copilot]
src.git = "https://github.com/copilot-emacs/copilot.el.git"
fetch.github = "copilot-emacs/copilot.el"

[emacs-term-title]
src.git = "https://github.com/CyberShadow/term-title.git"
fetch.github = "CyberShadow/term-title"
