[codestyle]
lang='go' # Check README.md for the supported languages.
[postprocess]
exec_on_each_problem_dir='goimports -w ./*.go'
[compiler]
compile_command='go build -o main main.go'
compile_only_when_diff_detected=true
[tester]
compile_before_testing=true
compile_only_when_diff_detected=true
timeout_adjustment=1.0
[submit.go]
exec_before_submit='rm ./combined.go && gottani . > ./combined.go'
exec_after_submit='rm ./combined.go'
submit_filename='./combined.go'
