[post-checkout]
follow = true

[post-checkout.commands.link-apply]
run = "make link-apply"

[post-merge]
follow = true

[post-merge.commands.link-apply]
run = "make link-apply"

[pre-commit]
follow = true
parallel = true

[pre-commit.commands.format-nix]
glob = "*.nix"
run = "nixfmt --quiet {staged_files} && git add {staged_files}"

[pre-commit.commands.format-fennel]
glob = "*.fnl"
run = "fnlfmt --fix {staged_files} && git add {staged_files}"

[pre-commit.commands.format-toml]
glob = "*.toml"
run = "taplo format {staged_files} && git add {staged_files}"
