[post-checkout]
follow = true

[post-checkout.commands.link-apply]
run = "make link-apply"

[post-merge]
follow = true

[post-merge.commands.link-apply]
run = "make link-apply"

[pre-commit]
[pre-commit.commands.format]
run = "make format"
