{
  modulesPath,
  config,
  pkgs,
  lib,
  ...
}:
with lib; {
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./orbstack.nix
    # Include the other configuration.
    ./user.nix
    ./openssh.nix
  ];
}
