[notebook]
dir = "~/zettelkasten"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
[lsp.completion]
note-label = "{{title-or-path}}"
note-filter-text = "{{title}} {{path}}"
use-additional-text-edits = true

[tool]
pager = "less -FIRX"
fzf-preview = "glow -s $HOME/.config/glamour/catppuccin-latte.json {-1}"

[filter]
last = "--sort modified- --limit 1"
today = "--created today --sort created"
this-week = "--sort created --created-after 'last monday'"

[alias]
amend = "zk edit last $@"
lazygit = "lazygit"
