[notebook]
dir = "~/zettelkasten"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[tool]
pager = "less -FIRX"
fzf-preview = "glow -s $HOME/.config/glamour/catppuccin-latte.json {-1}"

[filter]
last = "--sort modified- --limit 1"

[alias]
amend = "zk edit last $@"
