# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'
use = ['{{ name }}.zsh-theme']
hooks.post = '''
  source $ZDOTDIR/p10k.zsh
'''

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
apply = ["defer"]
hooks.post = '''
  bindkey '^r' zeno-history-selection
'''

[plugins.denovo]
github = "Warashi/denovo.zsh"
apply = ["defer"]

[plugins.denovo-fzf]
github = "Warashi/denovo-fzf"
hooks.post = '''
  bindkey "^x" denovo-fzf-ghq-cd
'''

[plugins.denovo-abbrev]
github = "Warashi/denovo-abbrev"
hooks.post = '''
  bindkey ' '  denovo-abbrev-expand
  bindkey '^m' denovo-abbrev-expand-and-accept-line
'''

[plugins.denovo-benchmark]
github = "Warashi/denovo-benchmark"

[plugins.denovo-complete]
github = "Warashi/denovo-complete"
hooks.post = '''
  bindkey '^i' denovo-complete
'''

[plugins.denovo-rootmake]
github = "Warashi/denovo-rootmake"

[plugins.zsh-terminal-title]
github = "AnimiVulpis/zsh-terminal-title"
apply = ["defer"]

[plugins.syntax-highlight]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.bd]
github = "Tarrasch/zsh-bd"
apply = ["defer"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
