[package]
name = "sekken-model"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
rmp-serde = "1.1.2"
serde = { version = "1.0.193", features = ["derive"] }
zstd = { version = "0.10.2", default-features = false, features = ["wasm"] }
