vim.api.nvim_set_keymap('', 'w', '<Plug>CamelCaseMotion_w', {silent=true})
vim.api.nvim_set_keymap('', 'b', '<Plug>CamelCaseMotion_b', {silent=true})
vim.api.nvim_set_keymap('', 'e', '<Plug>CamelCaseMotion_e', {silent=true})
vim.api.nvim_set_keymap('', 'ge', '<Plug>CamelCaseMotion_ge', {silent=true})
vim.api.nvim_del_keymap('s', 'w')
vim.api.nvim_del_keymap('s', 'b')
vim.api.nvim_del_keymap('s', 'e')
vim.api.nvim_del_keymap('s', 'ge')
vim.api.nvim_set_keymap('o', 'iw', '<Plug>CamelCaseMotion_iw', {silent=true})
vim.api.nvim_set_keymap('x', 'iw', '<Plug>CamelCaseMotion_iw', {silent=true})
vim.api.nvim_set_keymap('o', 'ib', '<Plug>CamelCaseMotion_ib', {silent=true})
vim.api.nvim_set_keymap('x', 'ib', '<Plug>CamelCaseMotion_ib', {silent=true})
vim.api.nvim_set_keymap('o', 'ie', '<Plug>CamelCaseMotion_ie', {silent=true})
vim.api.nvim_set_keymap('x', 'ie', '<Plug>CamelCaseMotion_ie', {silent=true})
