vim.keymap.set('', 'w', '<Plug>CamelCaseMotion_w', {silent=true})
vim.keymap.set('', 'b', '<Plug>CamelCaseMotion_b', {silent=true})
vim.keymap.set('', 'e', '<Plug>CamelCaseMotion_e', {silent=true})
vim.keymap.set('', 'ge', '<Plug>CamelCaseMotion_ge', {silent=true})
vim.keymap.set('o', 'iw', '<Plug>CamelCaseMotion_iw', {silent=true})
vim.keymap.set('x', 'iw', '<Plug>CamelCaseMotion_iw', {silent=true})
vim.keymap.set('o', 'ib', '<Plug>CamelCaseMotion_ib', {silent=true})
vim.keymap.set('x', 'ib', '<Plug>CamelCaseMotion_ib', {silent=true})
vim.keymap.set('o', 'ie', '<Plug>CamelCaseMotion_ie', {silent=true})
vim.keymap.set('x', 'ie', '<Plug>CamelCaseMotion_ie', {silent=true})

vim.keymap.del('s', 'w')
vim.keymap.del('s', 'b')
vim.keymap.del('s', 'e')
vim.keymap.del('s', 'ge')
