prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]
