[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file = ['$DPP_CONFIG_BASE/hooks/ddc.lua']

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-shell-native'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-mocword'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['pum.vim']
on_source = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = ['ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = ['ddc.vim']

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = ['ddc.vim']

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'call popup_preview#enable()'
on_source = ['ddc.vim']
