[[plugins]]
# rc/dpp.vim 内で読み込む
repo = 'Shougo/dpp.vim'
rtp = ''
depends = ['denops.vim']

[[plugins]]
# rc/dpp.vim 内で読み込む
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp.vim'
