[[plugins]]
repo = 'kuuote/lspoints'
on_event = ['BufRead', 'BufNewFile']
on_source = ['ddc-source-nvim-lsp']
hooks_file = ['$DPP_CONFIG_BASE/hooks/lspoints.fnl']

[[plugins]]
repo = 'Warashi/lspoints-hover'
on_source = ['lspoints']
