[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_cmd = ['TSInstall', 'TSUpdate', 'TSUninstall']
on_event = ['BufRead', 'BufNewFile']
hooks_file = '$DPP_CONFIG_BASE/hooks/treesitter.lua'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
on_source = ['nvim-treesitter']
lua_source = 'require("treesitter-context").setup()'
