[[plugins]]
repo = 'rcarriga/nvim-notify'
on_lua = ['notify']
hooks_file = '$DPP_CONFIG_BASE/hooks/nvim-notify.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = ['BufNewFile', 'BufRead']
lua_source = 'require("gitsigns").setup()'

[[plugins]]
repo = 'gen740/SmoothCursor.nvim'
on_event = ['BufNewFile', 'BufRead']
hooks_file = '$DPP_CONFIG_BASE/hooks/smooth-cursor.lua'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['InsertEnter']
lua_source = 'require("nvim-autopairs").setup()'

[[plugins]]
repo = 'monaqa/modesearch.nvim'
depends = ['kensaku.vim']
on_lua = ['modesearch']
hooks_file = '$DPP_CONFIG_BASE/hooks/modesearch.lua'

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = ['StartupTime']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = ['Deol']
hook_add = '''
  nnoremap <leader>t <Cmd>execute 'Deol' '-toggle' '-cwd='.('%'->expand()->fnamemodify(':h'))<CR>
  let g:deol#prompt_pattern = '❯ '
  let g:deol#floating_border = 'single'
'''

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
on_cmd = ['FuzzyMotion']
depends = ['kensaku.vim']
hook_add = '''
  nnoremap <leader>f <Cmd>FuzzyMotion<CR>
  let g:fuzzy_motion_matchers = ['fzf', 'kensaku']
'''

[[plugins]]
repo = 'Warashi/sekken'
on_source = ['ddc.vim']
hooks_file = '$DPP_CONFIG_BASE/hooks/sekken.vim'

# [[plugins]]
# repo = 'vim-skk/skkeleton'
# on_source = ['ddc.vim']
# on_event = ['InsertEnter', 'CmdlineEnter', 'TermOpen']
# hooks_file = '$DPP_CONFIG_BASE/hooks/skkeleton.lua'
# 
# [[plugins]]
# repo = 'delphinus/skkeleton_indicator.nvim'
# on_source = ['skkeleton']
# lua_source = '''
#   require("skkeleton_indicator").setup({
#     row = 1,
#     col = -6,
#     border = "double",
#     fadeOutMs = 1000,
#     eijiHlName = "String",
#     hiraHlName = "String",
#     kataHlName = "String",
#     hankataHlName = "String",
#     zenkakuHlName = "String",
#     abbrevHlName = "String",
#   })
# '''

[[plugins]]
repo = 'nvim-zh/colorful-winsep.nvim'
on_event = ['WinNew']
lua_source = '''
  require('colorful-winsep').setup()
'''

[[plugins]]
repo = 'github/copilot.vim'
on_cmd = ['Copilot']
on_event = ['InsertEnter']

[[plugins]]
repo = 'lambdalisue/gin.vim'
on_cmd = ['Gin', 'GinStatus']
on_ft = ['gitcommit']
hook_add = '''
  nnoremap <silent> <leader>g <Cmd>tabnew +GinStatus<CR>
'''

[[plugins]]
repo = 'rhysd/conflict-marker.vim'
on_event = ['BufRead', 'StdinReadPre']

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = ['BufRead', 'BufNewFile']
