[[plugins]]
repo = 'lambdalisue/guise.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'glacambre/firenvim'
if = 'exists("g:started_by_firenvim")'
hook_post_update = 'call firenvim#install(0)'
hook_add = '''
  if exists('g:started_by_firenvim')
    set laststatus=0
    set showtabline=0
  endif
'''
