[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
lua_source = '''
  require("catppuccin").setup({
    integrations = {
      aerial = true,
      bufferline = true,
      gitsigns = true,
      illuminate = true,
      lsp_trouble = true,
      mason = true,
      notify = true,
      nvimtree = true,
      sandwich = true,
      semantic_tokens = true,
      treesitter = true,
      treesitter_context = true,

      native_lsp = {
        enabled = true,
      },
    },
  })
  vim.cmd([[colorscheme catppuccin-mocha]])
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'rcarriga/nvim-notify'
lua_source = '''
  local notify = require("notify")
  notify.setup({
    stages = "slide",
  })
  vim.notify = notify
'''

[[plugins]]
repo = 'folke/noice.nvim'
lua_source = '''
  require("noice").setup({
    lsp = {
      override = {
        ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
        ["vim.lsp.util.stylize_markdown"] = true,
      },
    },
    presets = {
      bottom_search = true, -- use a classic bottom cmdline for search
      command_palette = true, -- position the cmdline and popupmenu together
      long_message_to_split = true, -- long messages will be sent to a split
      inc_rename = false, -- enables an input dialog for inc-rename.nvim
      lsp_doc_border = true, -- add a border to hover docs and signature help
    },
  })
'''
