[[plugins]]
repo = 'MunifTanjim/nui.nvim'
on_lua = ['nui']

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_lua = ['plenary']

[[plugins]]
repo = 'Shougo/pum.vim'
on_func = ['pum']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_func = ['openbrowser']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_func = ['nerdfont']

[[plugins]]
repo = 'tani/vim-artemis'
on_lua = ['artemis']
