[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
lua_source = 'require("nvim-web-devicons").setup({ default = true })'

[[plugins]]
repo = 'tyru/open-browser.vim'
