[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = ['InsertEnter', 'CmdlineEnter']

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_source = ['vim-vsnip']

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_source = ['vim-vsnip']
