[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = ['InsertEnter', 'CmdlineEnter']
if = 0

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_source = ['vim-vsnip', 'denippet.vim']

[[plugins]]
repo = 'uga-rosa/denippet.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
on_source = ['ddc.vim']
hooks_file = ['$DEIN_CONFIG_BASE/hooks/snippet.lua']
