[[plugins]]
name = 'shougo-s-github'
repo = 'Shougo/shougo-s-github'
if = 0

[[plugins]]
name = 'kuuote-dotvim'
repo = 'kuuote/dotvim'
if = 0

[[plugins]]
name = 'kyoh86-dotfiles'
repo = 'kyoh86/dotfiles'
if = 0
