[[plugins]]
name = 'shougo-s-github'
repo = 'Shougo/shougo-s-github'
if = 0

[[plugins]]
name = 'kuuote-dotvim'
repo = 'kuuote/dotvim'
if = 0

[[plugins]]
name = 'uga-rosa-dotfiles'
repo = 'uga-rosa/dotfiles'
if = 0
