[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/catppuccin.lua'
hook_post_update = 'CatppuccinCompile'

[[plugins]]
repo = 'rcarriga/nvim-notify'
on_lua = ['notify']
depends = ['catppuccin']
hooks_file = '$DEIN_CONFIG_BASE/hooks/nvim-notify.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['catppuccin']
on_event = ['BufNewFile', 'BufRead']
lua_source = 'require("gitsigns").setup()'

[[plugins]]
repo = 'gen740/SmoothCursor.nvim'
on_event = ['BufNewFile', 'BufRead']
hooks_file = '$DEIN_CONFIG_BASE/hooks/smooth-cursor.lua'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['InsertEnter']
lua_source = 'require("nvim-autopairs").setup()'

[[plugins]]
repo = 'monaqa/modesearch.nvim'
depends = ['kensaku.vim']
on_lua = ['modesearch']
hooks_file = '$DEIN_CONFIG_BASE/hooks/modesearch.lua'

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = ['StartupTime']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = ['Deol']
hook_add = '''
  nnoremap <leader>t <Cmd>execute 'Deol' '-toggle' '-cwd='.('%'->expand()->fnamemodify(':h'))<CR>
  let g:deol#prompt_pattern = '❯ '
  let g:deol#floating_border = 'single'
'''

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
on_cmd = ['FuzzyMotion']
depends = ['kensaku.vim']
hook_add = '''
  nnoremap <leader>f <Cmd>FuzzyMotion<CR>
  let g:fuzzy_motion_matchers = ['fzf', 'kensaku']
'''

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = { ict = '<Plug>(skkeleton-enable)' }
hooks_file = '$DEIN_CONFIG_BASE/hooks/skkeleton.lua'
hook_source = '''
  call skkeleton#initialize()
'''

[[plugins]]
repo = 'delphinus/skkeleton_indicator.nvim'
on_source = ['skkeleton']
lua_source = '''
  require("skkeleton_indicator").setup({
    row = 1,
    col = -6,
    border = "double",
    fadeOutMs = 1000,
    eijiHlName = "String",
    hiraHlName = "String",
    kataHlName = "String",
    hankataHlName = "String",
    zenkakuHlName = "String",
    abbrevHlName = "String",
  })
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_event = ['InsertEnter']
hook_source = '''
  let g:signature_help_config = #{contentsStyle: "remainingLabels", viewStyle: "virtual" }
  call signature_help#enable()
'''

[[plugins]]
repo = 'rebelot/heirline.nvim'
on_event = ['VimEnter']
hooks_file = '$DEIN_CONFIG_BASE/hooks/heirline.lua'
depends = ['nvim-navic', 'catppuccin']

[[plugins]]
repo = 'nvim-zh/colorful-winsep.nvim'
on_event = ['WinNew']
lua_source = '''
  require('colorful-winsep').setup()
'''
