[[plugins]]
repo = 'rcarriga/nvim-notify'
on_lua = ['notify']
depends = ['catppuccin']
hooks_file = '$DEIN_CONFIG_BASE/hooks/nvim-notify.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['catppuccin']
on_event = ['BufNewFile', 'BufRead']
lua_source = 'require("gitsigns").setup()'

[[plugins]]
repo = 'gen740/SmoothCursor.nvim'
on_event = ['BufNewFile', 'BufRead']
hooks_file = '$DEIN_CONFIG_BASE/hooks/smooth-cursor.lua'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['InsertEnter']
lua_source = 'require("nvim-autopairs").setup()'

[[plugins]]
repo = 'monaqa/modesearch.nvim'
on_lua = ['modesearch']
hooks_file = '$DEIN_CONFIG_BASE/hooks/modesearch.lua'

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = ['Fern']
hook_add = '''
  let g:fern#default_hidden = 1
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
on_source = ['fern.vim']
hook_source = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = ['fern.vim']
hook_add = '''
  let g:fern#renderer = "nerdfont"
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = ['fern.vim']

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = ['StartupTime']

[[plugins]]
repo = 'yutkat/confirm-quit.nvim'
on_event = ['CmdlineEnter']
lua_source = 'if vim.g.neovide then require("confirm-quit").setup() end'
