[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'lambdalisue/guise.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'
hook_add = '''
  nnoremap <silent> <leader>g <Cmd>tabnew +GinStatus<CR>
'''

[[plugins]]
repo = 'rhysd/conflict-marker.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
