[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/catppuccin.lua'
hook_post_update = 'CatppuccinCompile'

[[plugins]]
repo = 'vim-skk/skkeleton'
hooks_file = '$DEIN_CONFIG_BASE/hooks/skkeleton.lua'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'call popup_preview#enable()'

[[plugins]]
repo = 'matsui54/denops-signature_help'
hook_source = '''
  let g:signature_help_config = #{contentsStyle: "remainingLabels", viewStyle: "virtual" }
  call signature_help#enable()
'''

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
hook_add = '''
  let g:loaded_netrw = 1
  let g:loaded_netrwPlugin = 1
  let g:loaded_netrwSettings = 1
  let g:loaded_netrwFileHandlers = 1
'''

[[plugins]]
repo = 'rebelot/heirline.nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/heirline.lua'
depends = ['nvim-navic', 'catppuccin']

[[plugins]]
repo = 'lambdalisue/guise.vim'

[[plugins]]
repo = 'lambdalisue/gin.vim'
hook_add = '''
  nnoremap <silent> <leader>g <Cmd>tabnew +GinStatus<CR>
'''

[[plugins]]
repo = 'APZelos/blamer.nvim'
hook_add = '''
  let g:blamer_enabled = 1
  nnoremap <silent> <leader>b <Cmd>BlamerToggle<CR>
'''
