[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/catppuccin.lua'

[[plugins]]
repo = 'rcarriga/nvim-notify'
hooks_file = '$DEIN_CONFIG_BASE/hooks/nvim-notify.lua'
