[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/catppuccin.lua'

[[plugins]]
repo = 'rcarriga/nvim-notify'
depends = ['catppuccin']
hooks_file = '$DEIN_CONFIG_BASE/hooks/nvim-notify.lua'

[[plugins]]
repo = 'gen740/SmoothCursor.nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/smooth-cursor.lua'

[[plugins]]
repo = 'windwp/nvim-autopairs'
lua_source = 'require("nvim-autopairs").setup()'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['catppuccin']
lua_source = 'require("gitsigns").setup()'

[[plugins]]
repo = 'monaqa/modesearch.nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/modesearch.lua'

[[plugins]]
repo = 'vim-skk/skkeleton'
hooks_file = '$DEIN_CONFIG_BASE/hooks/skkeleton.lua'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'call popup_preview#enable()'

[[plugins]]
repo = 'matsui54/denops-signature_help'
hook_source = '''
  g:signature_help_config = #{contentsStyle: "remainingLabels", viewStyle: "virtual" }
  call signature_help#enable()
'''

[[plugins]]
repo = 'github/copilot.vim'
hook_add = 'let g:copilot_no_maps = v:true'
