[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/catppuccin.lua'
hook_post_update = 'CatppuccinCompile'

[[plugins]]
repo = 'rcarriga/nvim-notify'
on_lua = ['notify']
depends = ['catppuccin']
hooks_file = '$DEIN_CONFIG_BASE/hooks/nvim-notify.lua'

[[plugins]]
repo = 'gen740/SmoothCursor.nvim'
on_event = ['BufNewFile', 'BufRead']
hooks_file = '$DEIN_CONFIG_BASE/hooks/smooth-cursor.lua'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['InsertEnter']
lua_source = 'require("nvim-autopairs").setup()'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['catppuccin']
lua_source = 'require("gitsigns").setup()'

[[plugins]]
repo = 'monaqa/modesearch.nvim'
on_lua = ['modesearch']
hooks_file = '$DEIN_CONFIG_BASE/hooks/modesearch.lua'

[[plugins]]
repo = 'vim-skk/skkeleton'
hooks_file = '$DEIN_CONFIG_BASE/hooks/skkeleton.lua'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'call popup_preview#enable()'

[[plugins]]
repo = 'matsui54/denops-signature_help'
hook_source = '''
  let g:signature_help_config = #{contentsStyle: "remainingLabels", viewStyle: "virtual" }
  call signature_help#enable()
'''

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = ['Fern']

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
hook_add = '''
  let g:loaded_netrw = 1
  let g:loaded_netrwPlugin = 1
  let g:loaded_netrwSettings = 1
  let g:loaded_netrwFileHandlers = 1
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
on_source = ['fern.vim']
hook_source = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = ['fern.vim']
hook_add = '''
  let g:fern#renderer = "nerdfont"
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = ['fern.vim']

[[plugins]]
repo = 'rebelot/heirline.nvim'
hooks_file = '$DEIN_CONFIG_BASE/hooks/heirline.lua'
depends = ['nvim-navic', 'catppuccin']

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = ['StartupTime']
