# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "867a3debf907cbd7c5b0eb8837354a1efc7c2db9";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "867a3debf907cbd7c5b0eb8837354a1efc7c2db9";
      fetchSubmodules = false;
      sha256 = "sha256-BEA5cQSNgAMOULM3uNMATYHtFwV7CXAsZYi5IT1kB8A=";
    };
    date = "2025-01-15";
  };
  emacs-src = {
    pname = "emacs-src";
    version = "emacs-30.0.93";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "emacs-30.0.93";
      fetchSubmodules = false;
      sha256 = "sha256-lcpB4lKD3tjvCn646hUyAskxWNCQwEJ0RX/ZddRBRRU=";
    };
    "etc/e/eterm-color.ti" = builtins.readFile ./emacs-src-emacs-30.0.93/etc/e/eterm-color.ti;
  };
  emacs-term-title = {
    pname = "emacs-term-title";
    version = "0a891957d4a6e2afc4176b555fc790d4c5bacd05";
    src = fetchFromGitHub {
      owner = "CyberShadow";
      repo = "term-title";
      rev = "0a891957d4a6e2afc4176b555fc790d4c5bacd05";
      fetchSubmodules = false;
      sha256 = "sha256-RS3zhlYyK9hh6WtEoLDLAKINriFGzA9V2s+zFuL8o0E=";
    };
    date = "2022-01-05";
  };
}
