[plugins.fzf]
fzf-tmux = true
fzf-options = "-1 -p 80%"
ghq-cd-preview = "glow -s $HOME/.config/glamour/catppuccin-latte.json {}/README.md"

[plugins.abbrev]
[[plugins.abbrev.snippets]]
name = "git"
keyword = "g"
snippet = "git"

[[plugins.abbrev.snippets]]
name = "ls -l"
keyword = "ll"
snippet = "ls -l"

[[plugins.abbrev.snippets]]
name = "ls -al"
keyword = "la"
snippet = "ls -al"

[[plugins.abbrev.snippets]]
name = "tmux new-session"
keyword = "tn"
snippet = "tmux new-session -AD -s $(hostname -s)"

[[plugins.abbrev.snippets]]
name = "kubectl"
keyword = "k"
snippet = "kubectl"

[[plugins.abbrev.snippets]]
name = "kubectx"
keyword = "kx"
snippet = "kubectx"

[[plugins.abbrev.snippets]]
name = "exit"
keyword = ":q"
snippet = "exit"
