contest = "config"
selected_language = "go"

[languages.go]
extension = "go"
language_id = "4026"

[languages.go.test]
compiler = "go1.14.1"
compile_arg = "build -o <TASK> <TASK>.go"
command = "./<TASK>"
tle_time = 1000
print_wrong_answer = true
