[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
lua_post_source = '''
  require('nvim-web-devicons').setup({ default = true })
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']
lua_add = '''
  local function skkeleton_init()
    vim.fn["skkeleton#config"]({
      useSkkServer = false,
      globalDictionaries = {
        vim.fn.expand("~/.config/skk/SKK-JISYO.L"),
        vim.fn.expand("~/.config/skk/SKK-JISYO.jawiki"),
      },
    })
    vim.fn["skkeleton#register_keymap"]("input", ";", "henkanPoint")
    vim.fn["skkeleton#register_kanatable"]("rom", {
      ["~"] = { "～" },
    })
  end
  vim.keymap.set("i", "<C-j>", "<Plug>(skkeleton-enable)", { silent = true })
  vim.api.nvim_create_autocmd("User", { pattern = "skkeleton-initialize-pre", callback = skkeleton_init })
'''
