[[plugins]]
name = 'catppuccin'
repo = 'catppuccin/nvim'
lua_post_source = '''
  require("catppuccin").setup({
    integrations = {
      aerial = true,
      bufferline = true,
      gitsigns = true,
      illuminate = true,
      lsp_trouble = true,
      mason = true,
      notify = true,
      nvimtree = true,
      sandwich = true,
      semantic_tokens = true,
      treesitter = true,
      treesitter_context = true,

      native_lsp = {
        enabled = true,
      },
    },
  })
  vim.cmd([[colorscheme catppuccin-mocha]])
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']
lua_add = '''
  local function skkeleton_init()
    vim.fn["skkeleton#config"]({
      useSkkServer = false,
      globalDictionaries = {
        vim.fn.expand("~/.config/skk/SKK-JISYO.L"),
        vim.fn.expand("~/.config/skk/SKK-JISYO.jawiki"),
      },
    })
    vim.fn["skkeleton#register_keymap"]("input", ";", "henkanPoint")
    vim.fn["skkeleton#register_kanatable"]("rom", {
      ["~"] = { "～" },
    })
  end
  vim.keymap.set("i", "<C-j>", "<Plug>(skkeleton-enable)", { silent = true })
  vim.api.nvim_create_autocmd("User", { pattern = "skkeleton-initialize-pre", callback = skkeleton_init })
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']
lua_post_source = '''
  vim.fn["popup_preview#enable"]()
'''
