[[plugins]]
repo = '~/.config/nvim/swim'
on_event = 'InsertEnter'
lua_source = '''
  require("swim")
'''

[[plugins]]
repo = 'RRethy/nvim-base16'
on_event = ['BufEnter']
hook_source = '''
  colorscheme base16-gruvbox-dark-medium
  highlight Visual gui=reverse
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'
on_event = ['BufEnter']

[[plugins]]
repo = 'hotwatermorning/auto-git-diff'
on_ft = 'gitrebase'

[[plugins]]
repo = 'folke/trouble.nvim'
on_cmd = ['TroubleToggle']
on_source = ['gitsigns.nvim']
lua_add = '''
  vim.keymap.set("n", "<leader>t", "<cmd>TroubleToggle<cr>", opts)
'''
lua_source = '''
  require("trouble").setup({})
'''


[[plugins]]
repo = 'stevearc/aerial.nvim'
on_cmd = ["AerialToggle!"]
lua_add = '''
  vim.keymap.set("n", "<leader>a", "<cmd>AerialToggle!<cr>")
'''
lua_source = '''
  require("aerial").setup({
    backends = {
      "lsp",
      "treesitter",
      "markdown",
      "man",
    },
    layout = {
      width = nil,
      min_width = 20,
      max_width = { 80, 0.5 },
      win_opts = {
        winblend = 30,
      },
      default_direction = "float",
      placement = "edge",
    },
    highlight_mode = "last",
    manage_folds = "auto",
    close_on_select = true,
    show_guides = true,
    float = {
      border = "rounded",
      relative = "win",
      height = nil,
      min_height = { 8, 0.1 },
      max_height = 0.9,
      override = function(conf, source_winid)
        conf.anchor = "NE"
        conf.col = vim.fn.winwidth(source_winid)
        conf.row = 0
        return conf
      end,
    },
  })
'''

